### ISSUE TITLE
Issues with lock screen and sleep mode

### ISSUE THREAD

**Issue by ghost** [TeamAntumbra/wintumbra#2]
Two issues to report here (Windows 8.1):

1) After I have Antumbra device up and running fine, if I lock the session and then unlock it, the application is no longer running and the colors don't update.  I have to go back in and restart the exe in order for things to work again.

2) If I put my machine in sleep mode, the Antumbra device illumination stays lit.

**Comment by walshie4** [comment]
These issues have been fixed in the [most recent release](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.1.10-beta). Thank you for reporting them!

**Comment by ghost** [comment]
Both of these issues are still present following upgrade to 1.2.6.0.

Windows 8.1, x64
Intel Core i7
16GB mem
ATI Radeon HD 4800

**Comment by walshie4** [comment]
Where are you getting version 1.2.6.0?

**Comment by ghost** [comment]
Ah, disregard, I had upgraded but not to the latest/greatest.  After 1.14.0, confirmed that putting computer to sleep turns off the Glow.  (1.2.6.0 errantly pulled from Glow driver number in Device Mgr... apologies.)

**Comment by walshie4** [comment]
Good to hear it's working now. :)
